<template>
    <div>
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAOJJREFUSEvFlOERgjAMhd/bRDbRTWQSdRLZRDaRTZ4X71qh9K6QAvYPx7XJl+QlIXY+3Nk/sgBJTwDXlfAHyXtqMwNIOgF4r3Qenrcku7FtDmBR3JyAjmRbArwAnJ2AnuSlBJDTeTBrSA7hZ1KiyvovAtTUPyt0moGnPdOKToROAbX1N9hAsslqUClu1vy4VSHJet8GzDsDIYMegK0N+/52kSRbD7Ymtjhx4GKJJG0hcAyO5Nf3DBAuAjD9X5re/wBLIyy9y2Wwpchx2MYaWHvaqqjtpHybllL23h83yd4IS3Yf49djGYR+ybYAAAAASUVORK5CYII="/>
                    </div>
</template>
