<template>
    <div>
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAPhJREFUSEvVlcERwjAMBDedQCfQCVQCVAJUAp1AJzDnQRnFdsgoJg/0SR6296S7OB0LV7fw+dQAO+AArILwJ3AFjn5fDfAKHuyXC7L+BpD6M3AB9kHQDdgAW+Bue/MOWgAajUZ78mPKAVIviNSri0hJvbqQenWRKgc8PuZqjppnpBQK7R/4kAPM4DnxnQRYi0USAm0URnulLQabBgP0HnqAGTxIQUC9lhZJqgHmJMh0FEnyAEtQUHR1ee+jB7RcETVKOrsGmBNRDxhEvQXgDxp7b+pgccBYGEZHZB/JL1LUX3jeA2VY162eLaWI6ltK/4TWxEwK+X/AG8p1PBnAc/6bAAAAAElFTkSuQmCC"/>
            </div>
</template>
