<template>
    <div>
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAIdJREFUSEvtlcsRgCAMRHc701KsRK1MSrGTODn4wQEiDnAiZ2ZfeDAJUblYOR8mQEQGAFukkZXkkmoyCTDCNXcHMJF0MYgHEBEpoYzkldsWUKL7d0bwDf6qeqo5QR3gKe+KzF/cFXVFt4EWs0g3mG6ynHIkx6/TVMPnDEh0s5k7OecKobPVAQezGVIZxlgo+AAAAABJRU5ErkJggg=="/>
    </div>
</template>
